name: Run Refresh Script
run-name: ${{ github.actor }} is refreshing data 🔄
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 14 * * *" # Everyday at 2 PM UTC (after daily data release at ~11:20 AM UTC)
  workflow_dispatch: # Allows manual triggering of the workflow
permissions:
  contents: write # allows the job's GITHUB_TOKEN to push commits
jobs:
  Run-Refresh-Script:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Install Playwright browsers & deps
        run: python -m playwright install --with-deps chromium
      - name: Run refresh script
        run: |
          chmod +x ./refresh.sh
          ./refresh.sh || exit 1
      - name: Configure git for GitHub Actions bot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Push changes to main if no errors
        if: success()
        run: |
          if git diff --quiet; then
            echo "No changes to commit";
          else
            git add .
            git commit -m "Automatic data refresh [skip ci]";
            git push origin main;
          fi
